language: node_js
node_js:
  - "8"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
#before_script:
  #- npm install -g firebase-tools
deploy:
  provider: firebase
  token:
    secure: b06CzTA3DY2kHGQ/VY9eSh/cUJjN0fJaxd5SAucXN48ylK7wOttqkV9qicCjLa0Woym248pnTw3cHRg2Y5njleBVxRaPqEO8zEge+OOWfYemtdFHCmhYpdOKFJf4esBerEnOMFeZuge/4vx8+TxsP2/vruFhYD9SLxAOdQTutLDBQu4Nnm+utYcpJ27a9JDkGfXls9m1PCURyjILiNZEHWegn+/LWM9RJU71CHenpGBWFuvaMOz8ZtZrtTplvtLg72mZTjj8Mlv5NueEzi82/5e7ci7aaPDmGk6RJCpk+RWo0F7APUzu6P2mPm1zLV0TDXNfuA7MKd6U3r806BQdUc9dWpKW/0WUfYdvIOfNDHDohw9x27NiMeRx8IKlZFWvPM1AWxAzpc7VcK/AatlTbbWRyohQrq1HXGR00TNR63zCaHngGGkklC0c2Ne/Xj9+LT0DBxFed1cEF531aa3Z3jOFVXttOQmj8d38vdBl9T/v0f+HzfsUTayd1QiFOyAWm3L+alyHEKYXGmNJbTeytpI+zf3nwNuQMpPTfo1MULujwoxRC+9jHChazpaaHvyCMtfYWRGx5rF916Xp7T35ZgbCqwgXEshU/B48/VvAfLXiVUrvGNPOMoKBTEhRTM8CVxLq244GChitz0hNDKWKUWFmBcmyiBn7toBNnLhT5Bw=
  project: "kp-ng-ecomm"